### ISSUE TITLE
2.0.0-beta.2 doesn't work with strapi@5.0.0-rc.1

### ISSUE THREAD

**Issue by jordanernult** [pluginpal/strapi-plugin-config-sync#129]
### Describe the bug

the tag 2.0.0-beta.2 doesn't work using strapi@5.0.0-rc.1. The panel admin doesn't build.

### Expected behavior

I would be able to use the admin panel with the last release candidate.

### Screenshots

![image](https://github.com/pluginpal/strapi-plugin-config-sync/assets/53581741/cb7bfa80-283a-49a2-9f33-fab65e6841e9)

### System

- Node.js version: 20.15.0
- NPM version: 10.8.1
- Strapi version: 5.0.0-rc.1
- Plugin version: 2.0.0-beta.2
- Database: sqlite
- Operating system: macOs

**Comment by boazpoolman** [comment]
Hi @jordanernult,

Thanks for reporting this bug!
I’ve resolved the issue in PR https://github.com/pluginpal/strapi-plugin-config-sync/pull/130.
Will release a new beta version shortly.

**Comment by jordanernult** [comment]
Hi @boazpoolman,
Great job, I was missing the addition of config-sync in renderAdmin function, in order to do the PR.

**Comment by boazpoolman** [comment]
This was released with version `v2.0.0-beta.3`.

Please report a new issue if you experience any other problems.
