### ISSUE TITLE
CLI command to skip confirmation not working

### ISSUE THREAD

**Issue by HeikkiYlipaavalniemi** [pluginpal/strapi-plugin-config-sync#151]
### Describe the bug

We are trying to setup CICD with config sync in Strapi and would like to import config changes automatically during deployment.

Currently it seems like `-y` flag is not working as described here: https://docs.pluginpal.io/config-sync/cli#flag--y---yes

### Steps to reproduce the behavior

1. Run the command `npm run cs import -y`

### Expected behavior

The configs should be imported without additional confirmation required.

### System

- Node.js version: 20
- NPM version: 10.8.3
- Strapi version: 4.25.9
- Plugin version: 1.2.6
- Database: MySQL
- Operating system: macOS (local) & Alpine Linux (Docker container)

**Comment by boazpoolman** [comment]
Hi @HeikkiYlipaavalniemi 

It looks like `npm` needs a different format for passing flags to a `script` as defined in your `package.json`.

Running the command as follows should work:

```
npm run cs import -- -y
```

I've updated the docs to reflect this change.
Thanks for reporting!

**Comment by HeikkiYlipaavalniemi** [comment]
Verified. This works.
