### ISSUE TITLE
[deprecated] addSettingsLink 

### ISSUE THREAD

**Issue by reslear** [pluginpal/strapi-plugin-config-sync#154]
console log deprecation warning 

![CleanShot 2024-11-06 at 16 45 17@2x](https://github.com/user-attachments/assets/45dd4f0a-4a03-4f82-8df4-28bece474170)

```log
[Tools]: the `to` property of your settings link is an absolute path. It should be relative to `/settings`. This has been corrected for you but will be removed in a future version of Strapi.

[Tools]: the `to` property of your settings link has `settings` as the first part of it's path. It should be relative to `settings` and therefore, not include it. This has been corrected for you but will be removed in a future version of Strapi.
```

**Comment by boazpoolman** [comment]
Thanks for noticing @reslear.

This, and all other warnings that originated from the plugin, are now fixed in [v3.0.2](https://github.com/pluginpal/strapi-plugin-config-sync/releases/tag/3.0.2).
