### ISSUE TITLE
Misaligned peer dependencies with strapi v5

### ISSUE THREAD

**Issue by rafal2228** [pluginpal/strapi-plugin-config-sync#155]
### Describe the bug

Latest available version (3.0.2) has misaligned peer dependencies with strapi v5. This causes issues when installing the plugin as npm is unable to resolve dependency tree.

### Steps to reproduce the behavior

1. Create a new project with strapi v5 - `npx create-strapi@latest my-strapi-project`
2. Go to project directory
3. Run `npm i strapi-plugin-config-sync@latest`

### Expected behavior

Installation should procced without any warnings

### Code snippets

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-strapi-project@0.1.0
npm ERR! Found: react-router-dom@6.28.0
npm ERR! node_modules/react-router-dom
npm ERR!   react-router-dom@"^6.0.0" from the root project
npm ERR!   peer react-router-dom@"^6.0.0" from @strapi/strapi@5.3.0
npm ERR!   node_modules/@strapi/strapi
npm ERR!     @strapi/strapi@"5.3.0" from the root project
npm ERR!     peer @strapi/strapi@"^5.0.0" from strapi-plugin-config-sync@3.0.2
npm ERR!     node_modules/strapi-plugin-config-sync
npm ERR!       strapi-plugin-config-sync@"3.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-router-dom@"^5.2.0" from strapi-plugin-config-sync@3.0.2
npm ERR! node_modules/strapi-plugin-config-sync
npm ERR!   strapi-plugin-config-sync@"3.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### System

- Node.js version: `v20.11.0`
- NPM version: `10.2.4`
- Strapi version: `5.3.0`
- Plugin version: `3.0.2`

### Additional context

Latest version of strapi defines [following peer deps](https://github.com/strapi/strapi/blob/c54031ab6fbd4c78763d48335568460f900fb245/packages/core/strapi/package.json):

```json
  "peerDependencies": {
    "react": "^17.0.0 || ^18.0.0",
    "react-dom": "^17.0.0 || ^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
```

Currently the plugin [specifies](https://github.com/pluginpal/strapi-plugin-config-sync/blob/14a0ae877bbdfa2e21ff96315027c449d0c698e1/package.json):

```json
  "peerDependencies": {
    "@strapi/strapi": "^5.0.0",
    "react": "^17.0.0 || ^18.0.0",
    "react-dom": "^17.0.0 || ^18.0.0",
    "react-router-dom": "^5.2.0",
    "styled-components": "^5.2.1"
  },
```

**Comment by boazpoolman** [comment]
Thanks @rafal2228

Will investigate.

**Comment by boazpoolman** [comment]
I've updated the peer dependencies in v3.0.3. Should work now!

Didn't know NPM was so strict about it's peer dependency management, pretty sweet.
