### ISSUE TITLE
config-sync is not displayed in strapi admin

### ISSUE THREAD

**Issue by jTanos** [pluginpal/strapi-plugin-config-sync#160]
### Describe the bug

Hello good afternoon, I installed the plugin following the steps described but no config-sync section appears in the strapi admin.
config-sync in the strapi admin.

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.17.1
- Plugin version: 1.2.6

**Comment by boazpoolman** [comment]
Hi @jTanos 

Thanks for reporting this issue. Can you confirm that the plugin is installed? You should be able to see in under the Plugins menu in the admin panel.

If you are able to post some screenshots we are able to better pinpoint the issue.

**Comment by jTanos** [comment]
Hi @boazpoolman 

Thanks for your prompt reply.
The plugin is installed but does not appear in the plugin menu in the administration panel. 

I share with you some screenshots.

![image](https://github.com/user-attachments/assets/b6817630-dba0-4ae5-b5ca-ef115eb97faf)
![image](https://github.com/user-attachments/assets/87a4966f-d47d-48bc-8411-c8fb6f44985d)

**Comment by jTanos** [comment]
Hi @boazpoolman

I tried uninstalling the plugin and reinstalling and now it does appear.
We can now consider it closed. Thank you very much!!!
