### ISSUE TITLE
Diff Viewer is broken when run strapi in develop mode

### ISSUE THREAD

**Issue by AmmonLin** [pluginpal/strapi-plugin-config-sync#164]
### Describe the bug

When use the Diff viewer to inspect the config changes, got the following error message in develop mode:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `ConfigDiff`.

the same message show on console many times.

### Steps to reproduce the behavior

1. `npx create-strapi-app@latest` and use all default settings.
2. `cd my-strapi-project && npm run develop`
3. create an admin user and login
4. Go to 'http://localhost:1337/admin/settings/config-sync' and `Make the initail export`
5. Change any settings to make config not up-to-date.
6. Click the `Config Name` to see diff
7. see error 

### Expected behavior

Diff viewer works as in the production mode.

### Screenshots

![image](https://github.com/user-attachments/assets/87ac64c6-8dce-456f-b04e-35c296cac940)

### Code snippets

N/A

### System

- Node.js version: 22.12.0
- NPM version: 9.9.3
- Strapi version: 5.6.0
- Plugin version: 3.1.0
- Database: sqlite
- Operating system:  Ubuntu 20.04.6 LTS in WSL (Windows 11 24H2)

### Additional context

N/A

**Comment by boazpoolman** [comment]
Hi @AmmonLin,

Thanks for reporting this bug.

Could you confirm the issue with version 3.0.4 of the plugin as well?

**Comment by AmmonLin** [comment]
> Could you confirm the issue with version 3.0.4 of the plugin as well?

@boazpoolman   3.0.3 and 3.0.4 also have this issue. 
 
 3.0.2 3.0.1 install fail on my computer.

2.1.0 works as well

**Comment by boazpoolman** [comment]
Thank you.
I will investigate the issue.

**Comment by boazpoolman** [comment]
Confirmed.

Probably related to https://github.com/Aeolun/react-diff-viewer-continued/issues/43

**Comment by boazpoolman** [comment]
I've patched the issue in [version 3.1.1](https://github.com/pluginpal/strapi-plugin-config-sync/releases/tag/3.1.1).

Thanks for reporting it, and Merry Christmas 🎄

**Comment by AmmonLin** [comment]
Thank you for your prompt  response and swift patch! ❤️
Merry Christmas 🎄
