### ISSUE TITLE
(minor) Config diff label in interface not visible in dark mode

### ISSUE THREAD

**Issue by paulpopus** [pluginpal/strapi-plugin-config-sync#53]
### Describe the bug

Only a minor bug but I thought I'd report it anyway, the "X config change" label in the UI is not visible when Strapi UI is in dark mode.

### Steps to reproduce the behavior
Enable dark mode in Strapi UI and go to /admin/settings/config-sync

### Expected behavior

Text to be visible.

### Screenshots

![image](https://user-images.githubusercontent.com/35137243/165144585-03661533-22f3-4888-9a39-5a22b45316ba.png)

### System
Latest Strapi 4 and latest module with dark mode.

Thanks again for all your work on this much needed plugin!

**Comment by boazpoolman** [comment]
Thanks @paulpopus for reporting this issue regardless of the impact :)

**Comment by SalahAdDin** [comment]
I found this bug too.

**Comment by boazpoolman** [comment]
This has been fixed and released with the [stable version 2.0.0](https://github.com/pluginpal/strapi-plugin-config-sync/releases/tag/2.0.0).
