### ISSUE TITLE
Dowload config

### ISSUE THREAD

**Issue by pcriadoperez** [pluginpal/strapi-plugin-config-sync#54]
## Feature request
Be able to download config files.

### Summary

I use strapi in Google Run, and as many dockerized containers used in production it is sometimes hard to have cli or file access. Therefore it would be great to have a button to download the exported config files from production environments.

### Why is it needed?

Can't access exported config in dockerized containers without access to cli or files.

### Suggested solution(s)

Have a button to download exported files.

**Comment by pcriadoperez** [comment]
Happy to collaborate on a PR on this, if you think it would be of benefit

**Comment by boazpoolman** [comment]
Hey @pcriadoperez,

I totally agree with you. This could be a great feature. If you’re willing to submit a PR that would be sweet!

So a couple things that came to my mind:

- I guess we would want to .zip the entire `config/sync/` folder and download that.
- It makes sense that if we can download the zip we can also upload it.
- I would say this deserves it’s own page in the admin. Another link below the `tool` link in the setting.
- Don’t think we should bother showing any kind of diff-viewer like in the tool.
- In the backend this could be its own service. The routes and controllers that call the service could be included in the current (main) ones.

Do you have experience building plugins for Strapi? If not you can always shoot me a message and I’ll be happy to help you out 🙂

**Comment by boazpoolman** [comment]
Just pinging @ae94 here and pasting his fork:
https://github.com/The-Real-Established/strapi-plugin-config-sync

Do you plan on making a PR of that fork?
I'd love to see this merged back to the main branch.

**Comment by boazpoolman** [comment]
Just re-opening as this has yet to be released.

**Comment by boazpoolman** [comment]
This has been implemented and released with [version 2.1.0](https://github.com/pluginpal/strapi-plugin-config-sync/releases/tag/2.1.0) for Strapi 5. 

Special thanks to @ae94 for implementing this feature ❤️
